project:
  type: website

website:
  title: "James Tyrrell"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - projects.qmd
      - about.qmd
      

format:
  html:
    theme: 
      - darkly
      - styles.scss
    toc: true



